version: '3'
services:
  server:
    build: .
    ports:
      - "50051:50051"
  client1:
    build: .
    command: ["./client"]
    tty: true
  client2:
    build: .
    command: ["./client"]
    tty: true
  client3:
    build: .
    command: ["./client"]
    tty: true